### ISSUE TITLE
Docker tests should setup MongoDB/Eve properly

### ISSUE THREAD

**Issue by mtorpey** [gap-packages/Memoisation#5]
Currently they're failing:
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/574120189

**Comment by olexandr-konovalov** [comment]
If this functionality is optional, perhaps you can run certain test files only if the presence of mongodb is detected? Then it will run a full test here, and partial elsewhere.

**Comment by mtorpey** [comment]
Good idea – the MongoDB stuff doesn't *really* have to be tested on Docker.  However, since the test suite is supposed to test whether the whole package works, the default should probably be that it fails on a system without MongoDB.  Perhaps a good solution would be some explicit flag to disable mongodb tests, and then this flag could be set in Docker?  I'll discuss with you in person next week. :)

**Comment by olexandr-konovalov** [comment]
Can't you detect if mongodb is available from GAP?

**Comment by mtorpey** [comment]
We could, but I'm reluctant.  If MongoDB isn't installed when it should be, I want the tests to fail (e.g. on this repo's Travis, or on my own PC).  If the tests are disabled automatically, then it'll be harder to notice if something goes wrong.

That said, I don't mind an explicit option to disable a part of the suite.  Would PR #6 be usable by Docker?

(forgive me if I'm out of sync, by the way – Cernay has a poor Internet connection! :grin:)

**Comment by mtorpey** [comment]
We merged a solution (#6) and we should see if the Docker tests now pass.

**Comment by mtorpey** [comment]
#7 says that "#5 is fixed".  That's good enough for me! :)
